### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by b0yaux** [smthemex/ComfyUI_ParlerTTS#1]
Following the installing instructions, I keep getting 'import failed' in ComfyUI (through manager), and no TTS nodes are available.
![image](https://github.com/smthemex/ComfyUI_ParlerTTS/assets/164493605/6c2427ea-9ec3-428c-b047-86f2a637b256)

**Comment by b0yaux** [comment]
dependencies installed in appdata instead of comfyui site packages

**Comment by smthemex** [comment]
you can us“ pip install git+https://github.com/huggingface/parler-tts.git  ”install the dependencies ，Manager installation is currently not supported。

**Comment by smthemex** [comment]
> dependencies installed in appdata instead of comfyui site packages

Perhaps the portable version of ComfyUI was not considered, and now this bug has been fixed
