### ISSUE TITLE
IMPORT FAILED IN COMFY

### ISSUE THREAD

**Issue by aifuzz59** [smthemex/ComfyUI_ParlerTTS#2]
I did update ComfyUI and used a fresh install of Comfy but keep getting this error

  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_Experiments\ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\__init__.py", line 5, in <module>
    from .parler_tts_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_Experiments\ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\parler_tts_node.py", line 5, in <module>
    from parler_tts import ParlerTTSForConditionalGeneration
ModuleNotFoundError: No module named 'parler_tts'

Cannot import D:\ComfyUI_Experiments\ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS module for custom nodes: No module named 'parler_tts'

   0.0 seconds (IMPORT FAILED): D:\ComfyUI_Experiments\ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS

**Comment by smthemex** [comment]
Thank you. After the ComfyUI update, this issue will cause module import to fail. Now that I have updated the node code, you can try again. Please pay attention to the instructions for use

**Comment by smthemex** [comment]
> I did update ComfyUI and used a fresh install of Comfy but keep getting this error
> 
> File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\ComfyUI_Experiments\ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS__init__.py", line 5, in from .parler_tts_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "D:\ComfyUI_Experiments\ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\parler_tts_node.py", line 5, in from parler_tts import ParlerTTSForConditionalGeneration ModuleNotFoundError: No module named 'parler_tts'
> 
> Cannot import D:\ComfyUI_Experiments\ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS module for custom nodes: No module named 'parler_tts'
> 
> 0.0 seconds (IMPORT FAILED): D:\ComfyUI_Experiments\ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS

Perhaps the portable version of ComfyUI was not considered, and now this bug has been fixed  20240424
