### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by zhenyuanzhou** [smthemex/ComfyUI_ParlerTTS#5]
isin() received an invalid combination of arguments - got (elements=Tensor, test_elements=int, ), but expected one of:
 * (Tensor elements, Tensor test_elements, *, bool assume_unique, bool invert, Tensor out)
 * (Number element, Tensor test_elements, *, bool assume_unique, bool invert, Tensor out)
 * (Tensor elements, Number test_element, *, bool assume_unique, bool invert, Tensor out)

!!! Exception during processing!!! object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "F:\ComfyUI-master\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI-master\execution.py", line 95, in get_output_data
    output_is_list = [False] * len(results[0])
TypeError: object of type 'NoneType' has no len()

**Comment by smthemex** [comment]
这个有段时间没有维护了，我回头更新一下，因为现在comfyUI已经支持audio的文件的保存 。

**Comment by phr00t** [comment]
This was never fixed and is still a problem.

**Comment by smthemex** [comment]
There will be an update for version V2 today
