### ISSUE TITLE
Import failed when starting

### ISSUE THREAD

**Issue by liberteus** [smthemex/ComfyUI_ParlerTTS#8]
On windows, with ComfyUI updated, went through all command lines from the installation instructions, yet I still get the following:

> Warning: Missing Node Types
> When loading the graph, the following node types were not found:
> 
> ParlerTTS_LoadModel
> ParlerTTS_Sampler
> No selected item
> Nodes that have failed to load will show as red on the graph.

ComfyUI Manager tells me "Import failed" above the ComfyUI_ParlerTTS node.

**Comment by smthemex** [comment]
New update need transformers>=4.43.0, you can :pip show  transformers, to find you  transformers version.

**Comment by liberteus** [comment]
This is what I get:
> C:\Users\*******\Documents\AI\ComfyUI_windows_portable\python_embeded>python -m pip show transformers
> Name: transformers
> Version: 4.44.0
> Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
> Home-page: https://github.com/huggingface/transformers
> Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
> Author-email: transformers@huggingface.co
> License: Apache 2.0 License
> Location: C:\Users\*******\Documents\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages
> Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm

**Comment by smthemex** [comment]
Can you provide detailed information about the import failure?

**Comment by liberteus** [comment]
Here's the result when I start ComfyUI with the json already loaded in the UI:

> C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
>   warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.jsonTraceback (most recent call last):
>   File "C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\__init__.py", line 5, in <module>
>     from .parler_tts_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\parler_tts_node.py", line 7, in <module>
>     from .parler_tts import ParlerTTSForConditionalGeneration
>   File "C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\parler_tts\__init__.py", line 7, in <module>
>     from .dac_wrapper import DACConfig, DACModel
>   File "C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\parler_tts\dac_wrapper\__init__.py", line 2, in <module>
>     from .modeling_dac import DACModel
>   File "C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\parler_tts\dac_wrapper\modeling_dac.py", line 2, in <module>
>     from ...dac.model import DAC
>   File "C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\dac\__init__.py", line 6, in <module>
>     import audiotools
> ModuleNotFoundError: No module named 'audiotools'
> 
> Cannot import C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ParlerTTS module for custom nodes: No module named 'audiotools'

**Comment by smthemex** [comment]
pip install git+https://github.com/descriptinc/audiotools 
or 
git clone https://github.com/descriptinc/audiotools
cd audiotools
pip install .

**Comment by liberteus** [comment]
> pip install git+https://github.com/descriptinc/audiotools or git clone https://github.com/descriptinc/audiotools cd audiotools pip install .

Which folder should I install audiotools?
C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages ?
C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes ?

Thanks a lot for your help by the way. Sure it will help other in the future.

**Comment by smthemex** [comment]
if using ComfyUI_windows_portable, under" C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\python_embeded"  dir ,open CMD,fill in : 
python.exe -m pip install  git+https://github.com/descriptinc/audiotools

**Comment by liberteus** [comment]
Thanks, I had tried that actually and I got an error nonetheless. I think I'm going to close the ticket as it is not related to your tool but rather to audiotools and my own comfyUI install etc. Let me know if you think this is the correct way to go, and I'll close the issue.

>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [6 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\GitUser\Documents\AI\ComfyUI_windows_portable\python_embeded\AppData\Local\Temp\pip-install-f63zojjn\matplotlib_71d08f0ad3a248278ce95ea01b03eddf\setup.py", line 38, in <module>
>           import setupext
>       ModuleNotFoundError: No module named 'setupext'
>       [end of output]

**Comment by smthemex** [comment]
Try:
python -m pip install descript-audio-codec

**Comment by liberteus** [comment]
Node works, now downloading the mini model, on my way to test it :)
